machine: acorn
account: emc
queue: workq
git-https: True
scheduler: pbs
corespernode: 128
compiler: [intel,gfortran]
#compiler: [gfortran]
branch: [develop]
intel:
     versions: 
       2019.3: 
         compiler: intel/19.1.3.304          
         netcdf: cray-netcdf/4.7.4.3 
         hdf5: cray-hdf5/1.12.0.3
         mpi:
           mpi: 
             module: cray-mpich/8.1.4
             pythontest: True
         extra_env_vars: 
            var1: ESMF_OS=Linux
            var2: ESMF_CXXCOMPILER=CC
            var3: ESMF_F90COMPILER=ftn
            var4: ESMF_CXXLINKER=CC
            var5: ESMF_F90LINKER=ftn
            var6: ESMF_MPIRUN=mpirun.unicos
            var7: ESMF_CXXCOMPILECPPFLAGS=-fPIC
            var8: ESMF_CXXLINKOPTS="-fPIC -lnetcdff -lnetcdff"
            var9: ESMF_NETCDF=$PWD/nc-config
         extra_commands: 
            cmd1: "sed -i 's/^aprun/mpiexec/' scripts/mpirun.unicos"
            cmd2: "sed -i 's/lmpi++/lfmpich/' build_config/Linux.intel.default/build_rules.mk"
     extramodule: PrgEnv-intel cray-pals
     unloadmodule: "PrgEnv-cray PrgEnv-gnu"
gfortran:
     versions: 
       10.2.0: 
         compiler: gcc/10.2.0
         netcdf: cray-netcdf/4.7.4.3
         hdf5: cray-hdf5/1.12.0.3
         mpi:
           mpich3: 
             module: cray-mpich/8.1.4
             pythontest: True
         extra_env_vars: 
            var1: ESMF_OS=Linux
            var2: ESMF_CXXCOMPILER=CC
            var3: ESMF_F90COMPILER=ftn
            var4: ESMF_CXXLINKER=CC
            var5: ESMF_F90LINKER=ftn
            var6: ESMF_MPIRUN=mpirun.unicos
            var7: ESMF_F90COMPILEOPTS="-fallow-argument-mismatch -fallow-invalid-boz"
            var8: ESMF_NFCONFIG=nf-config
            var9: ESMF_CXXLINKOPTS="-fPIC -lnetcdff -lnetcdff"
         extra_commands: 
            cmd1: "sed -i 's/aprun/mpiexec/' scripts/mpirun.unicos"
       
#      10.1.0: 
#        module: gcc/10.1.0
#        netcdf: cray-netcdf/4.7.4.0
#        mpi:
#          mpi: cray-mpich/8.0.15
     extramodule: PrgEnv-gnu cray-pals
     unloadmodule: "PrgEnv-cray PrgEnv-intel"
