machine: cheyenne
account: p48503002
queue: regular
partition: None
scheduler: pbs
corespernode: 36
compiler: [gfortran]
branch: [main]
headnodename: cheyenne6
gfortran:
    test_time: "2:00:00"
    versions: 
       7.4.0: 
         compiler: gnu/7.4.0
         netcdf: netcdf/4.7.3
         mpi:
           openmpi: 
             module: openmpi/4.0.3
#            pythontest: True
         extra_env_vars: 
           var1: ESMF_F90COMPILER=mpif90
