machine: chianti
scheduler: None
corespernode: 8
compiler: [gfortran]
branch: [develop,patch/8.1.1]
modulepath: /home/mpotts/spack/share/spack/modules/linux-linuxmint19-skylake 
intel:
     versions: 
         compiler: intel/18.0.5.274
         netcdf: netcdf/4.7.0
         mpi:
           intelmpi: 
             module: impi/2018.4.274
           mpiuni: 
             module: None
gfortran:
     build_time: "2:00:00"
     test_time: "2:30:00"
     versions: 
       9.3.0: 
         compiler: gcc/9.3.0-gcc-7.5.0
         netcdf: netcdf-c/4.7.4-gcc-9.3.0-openmpi
         netcdf-fortran: netcdf-fortran/4.5.3-gcc-9.3.0-openmpi  
         hdf5: hdf5/1.10.7-gcc-9.3.0-openmpi 
         mpi:
           openmpi: 
             module: openmpi/3.1.3-gcc-9.3.0  
             pythontest: True
         extra_env_vars: 
            var1: ESMF_NETCDF=nc-config
            var2: ESMF_NFCONFIG=nf-config
     extramodule: python
