--- 
account: nems
branch: 
  - develop
  - jedwards/pio_update2
compiler: 
  - intel
  - gfortran
  - pgi
corespernode: 40
gfortran: 
  test_time: "2:00:00"
  versions: 
    ? "9.2.0"
    : 
      compiler: gnu/9.2.0
      extra_commands: 
        cmd1: "tar xvfz ~/pytest-input.tar.gz"
      extra_env_vars: 
        var1: ESMF_NETCDF=split
        var2: ESMF_NETCDF_INCLUDE=$NETCDF/include
        var3: ESMF_NETCDF_LIBPATH=$NETCDF/lib
        var4: "ESMF_NETCDF_LIBS=\"-lnetcdff -lnetcdf -lhdf5_hl -lhdf5 $HDF5ExtraLibs\""
        var5: ESMF_NETCDF=nc-config
      hdf5: hdf5/1.10.5
      mpi: 
        mpiuni: 
          module: None
        openmpi: 
          module: openmpi/3.1.4
          mpi_env_vars: 
            var1: ESMF_MPIRUN=mpirun.srun
          pythontest: true
      netcdf: netcdf/4.7.2
    9.2.0b: 
      compiler: gnu/9.2.0
      extra_commands: 
        cmd1: "tar xvfz ~/pytest-input.tar.gz"
      mpi: 
        intelmpi: 
          module: impi/2020
          mpi_env_vars: 
            var1: ESMF_MPIRUN=mpirun.srun
          pythontest: true
      netcdf: None
    extramodule: cmake
git-https: true
intel: 
  versions: 
    ? "18.0.4"
    : 
      compiler: intel/18.0.5.274
      extra_commands: 
        cmd1: "tar xvfz ~/pytest-input.tar.gz"
      mpi: 
        intelmpi: 
          module: impi/2018.4.274
          mpi_env_vars: 
            var1: ESMF_MPIRUN=mpirun.srun
          pythontest: true
        mpiuni: 
          module: None
      netcdf: netcdf-hdf5parallel/4.7.4
    extramodule: cmake
machine: hera
nuopcbranch: develop
partition: hera
pgi: 
  build_time: "2:00:00"
  test_time: "2:00:00"
  versions: 
    18.1: 
      compiler: pgi/18.10
      mpi: 
        intelmpi: 
          module: impi/2018.0.4
          mpi_env_vars: 
            var1: ESMF_MPIRUN=mpirun.srun
      netcdf: None
    extramodule: cmake
queue: batch
scheduler: slurm
