machine: hera
account: da-cpu
queue: batch
partition: hera
scheduler: slurm
corespernode: 40
compiler: [intel,gfortran,pgi]
#compiler: [gfortran]
branch: [patch/8.1.1,develop]
intel:
     versions: 
       18.0.4: 
         compiler: intel/18.0.5.274
         netcdf: netcdf/4.7.0
         mpi:
           intelmpi: 
             module: impi/2018.4.274
             pythontest: True
             mpi_env_vars: 
               var1: ESMF_MPIRUN=mpirun.srun
           mpiuni: 
             module: None
gfortran:
     test_time: "2:00:00"
     versions: 
       9.2.0: 
         compiler: gnu/9.2.0
         netcdf: netcdf/4.7.2
         hdf5: hdf5/1.10.5
         mpi:
           intelmpi: 
             module: impi/2020
             pythontest: True
             mpi_env_vars: 
               var1: ESMF_MPIRUN=mpirun.srun
           openmpi: 
             module: openmpi/3.1.4
             pythontest: True
             mpi_env_vars: 
               var1: ESMF_MPIRUN=mpirun.srun
           mpiuni: 
             module: None
         extra_env_vars: 
            var1: ESMF_NETCDF=split
            var2: ESMF_NETCDF_INCLUDE=$NETCDF/include
            var3: ESMF_NETCDF_LIBPATH=$NETCDF/lib
            var4: ESMF_NETCDF_LIBS="-lnetcdff -lnetcdf -lhdf5_hl -lhdf5 $HDF5ExtraLibs"
            var5: ESMF_NETCDF=nc-config
pgi:
     test_time: "1:30:00"
     build_time: "1:20:00"
     versions: 
       18.10: 
         compiler: pgi/18.10 
         netcdf: None
         mpi:
           intelmpi: 
             module: impi/2018.0.4
             mpi_env_vars: 
               var1: ESMF_MPIRUN=mpirun.srun
