machine: orion
account: da-cpu
queue: batch
partition: orion
scheduler: slurm
corespernode: 40
compiler: [intel,gfortran]
branch: [develop]
intel:
   versions:
     2020: 
       compiler: intel/2020.2
       netcdf: netcdf/4.7.4
       mpi:
           intelmpi: 
             module: impi/2020.2
             pythontest: True
   extramodule: intelpython3
gfortran:
   versions:
     8.3.0: 
       compiler: gcc/8.3.0
       netcdf: netcdf/4.7.2
       mpi:
           openmpi: 
             module: openmpi/4.0.2
             pythontest: True
           mpiuni: 
             module: None
       extra_env_vars: 
         var1: LD_PRELOAD=/apps/gcc-8/gcc-8.3.0/lib64/libstdc++.so
   extramodule: intelpython3
#    10.2.0: 
#      module: gcc/10.2.0
#      netcdf: netcdf/4.7.4
#      mpi:
#          openmpi: openmpi/4.0.4
pgi:
   build_time: "2:00:00"
   test_time: "2:30:00"
   versions:
     2019: 
       compiler: pgi/2019 
       netcdf: netcdf/4.7.4
       mpi:
           openmpi: 
             module: openmpi/4.0.2
       extra_env_vars: 
         var1: ESMF_F90COMPILER=mpif90
         var2: ESMF_CXXCOMPILER=mpicxx
